dir_export_base: 'D:\Dropbox\LM2_Env\Image_Datasets\GroundTruth_SEG_Castilleja_Phase1' #'D:\Dropbox\LeafMachine2\data\archival_component_detector_data\final'

project_name: 'PLANT_Castilleja_pass_1'


accumulate_all_projects_in_run: True

fetch_reviewed_annotations_only: True

use_template_yaml_file: True

do_redo_export: True

do_partition_data: False
partition_ratio: 0.90 # percent sent to training set


include_annotations: [] # PLANT # [] for all labels
annotation_type_to_export: ['PLANT'] # 'SEG'
include_projects: ['PLANT_Castilleja_pass_1']
ignore_projects: []






