dir_export_base: 'D:\Dropbox\LM2_Env\Image_Datasets\GroundTruth_RULER_POINTS' #'D:\Dropbox\LeafMachine2\data\archival_component_detector_data\final'
project_name: 'GroundTruth_RULER_POINTS_revised_wPE'

annotation_type_to_export: ['RULER'] # 'PREP' OR 'PLANT' OR list
include_projects: []
ignore_projects: [] #['POINTS_Morton_sinus_only', 'POINTS_Morton_Quercus_stellata', 'POINTS_Morton_Quercus_mohriana']

fetch_reviewed_annotations_only: False
do_partition_data: False
partition_ratio: 0.90 # percent sent to training set. Then val / test each get 50% of remaining

accumulate_all_projects_in_run: True 
use_template_yaml_file: True

do_redo_export: False # False allows you to resume if there's a timeout error. Just delete the last project prior to fail
create_zip_of_project: False

# Sort compound leaves and simple leaves, by image
do_sort_compound_and_simple_leaves: False

# Export cropped bboxes as new jpg
do_save_cropped_bboxes_as_jpgs: False
do_save_colors_to_csv: False
include_annotations: [] # ['angle_apex'] # [] for all labels
# include_anno: ['Ruler','Barcode','Colorcard','Map','Envelope','Photo','Attached Item','Weights'] # PREP all: ['Ruler','Barcode','Colorcard','Label','Map','Envelope','Photo','Attached Item','Weights']
# max_annotations_saved_per_image_LEAF: 1000000000
# max_annotations_saved_per_image_ALL_OTHER_TYPES: 10000000000