ontology_name:
  PREP: 'cl0d9tzkz74vv102p2vm3dnig'
  ARCHIVAL: 'cl0d9tzkz74vv102p2vm3dnig'
  PLANT: 'ckzgk03is335l0z8m3fw5f77n'
  LEAF_SEG: 'ckzpykqizaqsm0zc95uxo9s9r'
  POINTS: 'cl3vvho6n45cv086qap2l3sy4'
  POINTS_Morton: 'cl9rg4sl32o3q07vd5aro7zsz'