dir_export_base: 'D:/Dropbox/LM2_Env/Image_Datasets/Herbarium_Sheet_Corners' # 'D:/Dropbox/LM2_Env/Image_Datasets/GroundTruth_KEYPOINTS' #'D:/Dropbox/LeafMachine2/data/archival_component_detector_data/final'
project_name: 'Herbarium_Sheet_Corners_split' # 'GroundTruth_POINTS_V2_uniform_spaced_oriented_traces_midvein15_petiole5'

annotation_type_to_export: ['POINTS'] # 'PREP' OR 'PLANT' OR list
include_projects: ['POINTS_Herbarium_Sheet_Corners']
ignore_projects: [] #['POINTS_Acacia_Prickles', 'POINTS_Morton_sinus_only'] #['POINTS_Morton_sinus_only', 'POINTS_Morton_Quercus_stellata', 'POINTS_Morton_Quercus_mohriana']

fetch_reviewed_annotations_only: False
do_partition_data: True
partition_ratio: 0.80 # percent sent to training set. Then val / test each get 50% of remaining

accumulate_all_projects_in_run: True 
use_template_yaml_file: True

do_redo_export: False # False allows you to resume if there's a timeout error. Just delete the last project prior to fail
create_zip_of_project: False

# Sort compound leaves and simple leaves, by image
do_sort_compound_and_simple_leaves: False

# For kepypoints, define how to space the points along the traced components
# max_pts defines the uniform # of points allowed. 30 for midvein, 10 for petiole
# midpoint: Takes verbatim groundtruth points. If more than max_pts, randomly deletes points
#           If less than max_pts, adds midpoints as new points
# uniform: midpoint + uniform -- Recompoutes the spacing so that all points are equidistant
# curvature: midpoint + curvature -- trues to space the points relative to the density of the points to better retain sharp curvature details 
trace_resize_method: "uniform"

# Export cropped bboxes as new jpg
do_save_cropped_bboxes_as_jpgs: True
do_save_colors_to_csv: True
include_annotations: [] # [] for all labels
# include_anno: ['Ruler','Barcode','Colorcard','Map','Envelope','Photo','Attached Item','Weights'] # PREP all: ['Ruler','Barcode','Colorcard','Label','Map','Envelope','Photo','Attached Item','Weights']
# max_annotations_saved_per_image_LEAF: 1000000000
# max_annotations_saved_per_image_ALL_OTHER_TYPES: 10000000000