leafmachine:
  LLM_version: chatGPT
  archival_component_detector:
    detector_iteration: PREP_final
    detector_type: Archival_Detector
    detector_version: PREP_final
    detector_weights: best.pt
    do_save_prediction_overlay_images: true
    ignore_objects_for_overlay: []
    minimum_confidence_threshold: 0.5
  cropped_components:
    binarize_labels: false
    binarize_labels_skeletonize: false
    do_save_cropped_annotations: false
    save_cropped_annotations:
    - label
    save_per_annotation_class: true
    save_per_image: false
  data:
    do_apply_conversion_factor: false
    include_darwin_core_data_from_combined_file: false
    save_individual_csv_files_landmarks: false
    save_individual_csv_files_measurements: false
    save_individual_csv_files_rulers: false
    save_individual_efd_files: false
    save_json_measurements: false
    save_json_rulers: false
  do:
    check_for_corrupt_images_make_vertical: true
    check_for_illegal_filenames: true
  logging:
    log_level: null
  modules:
    specimen_crop: false
  overlay:
    alpha_transparency_archival: 0.3
    alpha_transparency_plant: 0
    alpha_transparency_seg_partial_leaf: 0.3
    alpha_transparency_seg_whole_leaf: 0.4
    ignore_archival_detections_classes: []
    ignore_landmark_classes: []
    ignore_plant_detections_classes:
    - leaf_whole
    - specimen
    line_width_archival: 12
    line_width_efd: 12
    line_width_plant: 12
    line_width_seg: 12
    overlay_background_color: black
    overlay_dpi: 300
    save_overlay_to_jpgs: true
    save_overlay_to_pdf: false
    show_archival_detections: true
    show_landmarks: true
    show_plant_detections: true
    show_segmentations: true
  print:
    optional_warnings: true
    verbose: true
  project:
    batch_size: 40
    build_new_embeddings_database: false
    continue_run_from_partial_xlsx: ''
    dir_images_local: D:/Dropbox/LM2_Env/Image_Datasets/GBIF_BroadSample_3SppPerFamily1
    dir_output: D:/D_Desktop/LM2
    embeddings_database_name: EmbeddingsDB_all_asia_minimal_InRegion
    image_location: local
    num_workers: 2
    path_to_domain_knowledge_xlsx: D:/Dropbox/LeafMachine2/leafmachine2/transcription/domain_knowledge/AllAsiaMinimalasof25May2023_2__InRegion.xlsx
    prefix_removal: MICH-V-
    run_name: test
