# config_download_from_GBIF_all_images_in_file.yml
####################################################################################
### Directories ###
dir_home: '/home/brlab/Dropbox/LM2_Env/Image_Datasets/SET_Big_Leaf/csv/Alismataceae_Sagittaria'

dir_destination_images: '/home/brlab/Dropbox/LM2_Env/Image_Datasets/SET_Big_Leaf/Images_by_Family/Alismataceae_Sagittaria'
dir_destination_csv: '/home/brlab/Dropbox/LM2_Env/Image_Datasets/SET_Big_Leaf/csv_downloaded/Alismataceae_Sagittaria'

is_custom_file: False
col_url: 'url'
col_name: 'lab_code'
# Use for custom
filename_img: 'P_serotina_79_urls.csv' # 'spines_images.txt' 'prickles_images.txt'

####################################################################################
### Exisitng Files ###
# Darwin Core Occurance File
filename_occ: 'occ_selected.csv'

####################################################################################
# Darwin Core Images File
filename_img: 'img_selected.csv' # 'spines_images.txt' 'prickles_images.txt'

####################################################################################
### Files that will be created ###
# Set the filename of a new csv containing the merged records from images and occ
#      filename_combined: 'combined_XXXXXXX.csv'
# filename_combined: 'combined_Fagaceae.csv' # appends to this file 
filename_combined: 'combined_downloaded.csv'

####################################################################################
### Set bounds ###
MP_low: 1
MP_high: 200
do_resize: False

####################################################################################
### Parallelization ###
n_threads: 16 # OR int in range 1:32, (usually 8-12) set to None to use number of local CPU cores + 4

####################################################################################
### Ignore Problematic Herbaria ###           download_all_images_in_images_csv(cfg) 
# Some herbaria (MNHM, or Naturalis Biodiversity Center...) have server/broken link issues frequently
# Set to True if you get long timeout errors
# Recommend = True
ignore_banned_herb: False 
# You can add your own banned herbs here.
# Add to the list based on the url stems from the 'identifier' column in the images.csv.
# Eg. 'http://mediaphoto.mnhn.fr/media/144135118650898Vf4SNC2P5ot2SW'  -->  'mediaphoto.mnhn.fr'
banned_url_stems: [] #['mediaphoto.mnhn.fr'] # ['mediaphoto.mnhn.fr', 'stock.images.gov'] etc....
