####################################################################################
### Directories ###
dir_home: 'D:/Dropbox/LM2_Env/Image_Datasets/SET_Big_Leaf/DWC_Big_Leaf/Araceae_Monstera' #'/home/brlab/Dropbox/LM2_Env/Image_Datasets/SET_Acacia'

dir_destination_images: 'D:/Dropbox/LM2_Env/Image_Datasets/SET_Big_Leaf/images/Araceae_Monstera'
dir_destination_csv: 'D:/Dropbox/LM2_Env/Image_Datasets/SET_Big_Leaf/csv/Araceae_Monstera'

####################################################################################
### Exisitng Files ###
# Darwin Core Occurance File
filename_occ: 'occurrence.txt'

####################################################################################
# Darwin Core Images File
filename_img: 'multimedia.txt'


filename_occ_appended: 'occ_selected.csv'
filename_img_appended: 'img_selected.csv'
filename_combined: 'combined_selected.csv'

do_shuffle_occ: True

n_imgs_per_species: 25
n_imgs_per_genus: null
n_imgs_per_family: null
n_imgs_total: null