# To use default value, set to null
leafmachine:
    do:
        check_for_illegal_filenames: True 
        check_for_corrupt_images_make_vertical: True
        run_leaf_processing: True
    print:
        verbose: True
        optional_warnings: True

    logging:
        log_level: null

    # Overall Project Input Settings
    project:
        # Project Output Dir
        dir_output: ['demo', 'demo_output']
        run_name: 'test_run' #'images_short_TEST' #'images_short_landmark'
        # If location is GBIF, set the config in:
        #       LeafMachine2/configs/config_download_from_GBIF_all_images_in_file OR
        #       LeafMachine2/configs/config_download_from_GBIF_all_images_in_filter
        image_location: 'local' # str |FROM| 'local' or 'GBIF'
        GBIF_mode: 'all' # str |FROM| 'all' or 'filter'. All = config_download_from_GBIF_all_images_in_file.yml Filter = config_download_from_GBIF_all_images_in_filter.yml
        batch_size: 50 #null # null = all
        num_workers: 2 # int |DEFAULT| 4 # More is not always better. Most hardware loses performance after 4
        # If *not* using local, set the following 4 to null
        # If providing occ and img, then a combined will be generated
        # If providing combined, then set images and occ to null
        dir_images_local: ['demo', 'demo_images'] # str | full path 
        
        path_combined_csv_local: null # str | full path 
        path_occurrence_csv_local: null # 'D:\Dropbox\LM2_Env\Image_Datasets\SET_Acacia\armature_occurrence.csv'  # str | full path 
        path_images_csv_local: null # 'D:\Dropbox\LM2_Env\Image_Datasets\SET_Acacia\prickles_images.csv'  # str | full 

        use_existing_plant_component_detections: null # str | full path # null for unprocessed images
        use_existing_archival_component_detections: null # str | full path # null for unprocessed images

        process_subset_of_images: False
        dir_images_subset: ''
        n_images_per_species: 10
        species_list: ''


    cropped_components:
        # empty list for all, add to list to IGNORE, lowercase, comma seperated
        # archival |FROM| 
        #           ruler, barcode, colorcard, label, map, envelope, photo, attached_item, weights
        # plant |FROM| 
        #           leaf_whole, leaf_partial, leaflet, seed_fruit_one, seed_fruit_many, flower_one, flower_many, bud, specimen, roots, wood
        do_save_cropped_annotations: True
        save_cropped_annotations: ['label','ruler'] # 'save_all' to save all classes
        save_per_image: False # creates a folder for each image, saves crops into class-names folders
        save_per_annotation_class: True # saves crops into class-names folders
        binarize_labels: True
        binarize_labels_skeletonize: True

    modules:
        armature: False
        specimen_crop: False

    data:
        save_json_rulers: False
        save_json_measurements: False
        save_individual_csv_files_rulers: False
        save_individual_csv_files_measurements: False
        include_darwin_core_data_from_combined_file: False
        do_apply_conversion_factor: True


    overlay:
        save_overlay_to_pdf: True
        save_overlay_to_jpgs: True
        overlay_dpi: 300 # int |FROM| 100 to 300
        overlay_background_color: 'black' # str |FROM| 'white' or 'black'

        show_archival_detections: True
        ignore_archival_detections_classes: []
        show_plant_detections: True
        ignore_plant_detections_classes: ['leaf_whole', 'leaf_partial', 'specimen']
        show_segmentations: True
        show_landmarks: True
        ignore_landmark_classes: []

        line_width_archival: 1 # int
        line_width_plant: 1 # int
        line_width_seg: 1 # int # thick = 12
        line_width_efd: 1 # int # thick = 3
        alpha_transparency_archival: 0.3  # float between 0 and 1
        alpha_transparency_plant: 0
        alpha_transparency_seg_whole_leaf: 0.4
        alpha_transparency_seg_partial_leaf: 0.3


    # Configure Plant Component Detector
    plant_component_detector:
        # ./leafmachine2/component_detector/runs/train/detector_type/detector_version/detector_iteration/weights/detector_weights
        detector_type: 'Plant_Detector' 
        detector_version: 'PLANT_GroupAB_200'
        detector_iteration: 'PLANT_GroupAB_200'
        detector_weights: 'best.pt'
        minimum_confidence_threshold: 0.1 
        do_save_prediction_overlay_images: True
        ignore_objects_for_overlay: [] #['leaf_partial'] # list[str] # list of objects that can be excluded from the overlay # all = null
    

    # Configure Archival Component Detector
    archival_component_detector:
        # ./leafmachine2/component_detector/runs/train/detector_type/detector_version/detector_iteration/weights/detector_weights
        detector_type: 'Archival_Detector' 
        detector_version: 'PREP_final'
        detector_iteration: 'PREP_final'
        detector_weights: 'best.pt'
        minimum_confidence_threshold: 0.5
        do_save_prediction_overlay_images: True
        ignore_objects_for_overlay: [] # list[str] # list of objects that can be excluded from the overlay # all = null
    

    landmark_detector:
        # ./leafmachine2/component_detector/runs/train/detector_type/detector_version/detector_iteration/weights/detector_weights
        landmark_whole_leaves: True
        landmark_partial_leaves: False
        
        detector_type: 'Landmark_Detector_YOLO' 
        detector_version: 'Landmarks'
        detector_iteration: 'Landmarks'
        detector_weights: 'last.pt'
        minimum_confidence_threshold: 0.1
        do_save_prediction_overlay_images: True
        ignore_objects_for_overlay: [] # list[str] # list of objects that can be excluded from the overlay # all = null
        use_existing_landmark_detections: null # null for unprocessed images

        do_show_QC_images: False
        do_save_QC_images: True

        do_show_final_images: False
        do_save_final_images: True
    

    ruler_detection:
        detect_ruler_type: True # only True right now
        ruler_detector: 'ruler_classifier_38classes_v-1.pt'  # MATCH THE SQUARIFY VERSIONS
        ruler_binary_detector: 'model_scripted_resnet_720_withCompression.pt'  # MATCH THE SQUARIFY VERSIONS
        minimum_confidence_threshold: 0.4
        save_ruler_validation: True # save_ruler_class_overlay: True
        save_ruler_validation_summary: True  # save_ruler_overlay: True 
        save_ruler_processed: False # this is the angle-corrected rgb ruler


    # Configure Archival Component Detector
    leaf_segmentation:
        segment_whole_leaves: True
        segment_partial_leaves: True 

        keep_only_best_one_leaf_one_petiole: True

        save_segmentation_overlay_images_to_pdf: True
        save_each_segmentation_overlay_image: True
        save_individual_overlay_images: True # Not recommended, will create many files. Useful for QC or presentation
        overlay_line_width: 1 # int |DEFAULT| 1 
    
        use_efds_for_png_masks: False # requires that you calculate efds --> calculate_elliptic_fourier_descriptors: True
        save_masks_color: True
        save_full_image_masks_color: True
        save_rgb_cropped_images: True

        find_minimum_bounding_box: True

        calculate_elliptic_fourier_descriptors: True # bool |DEFAULT| True 
        elliptic_fourier_descriptor_order: null # int |DEFAULT| 40
        
        segmentation_model: 'GroupB_Dataset_100000_Iter_1176PTS_512Batch_smooth_l1_LR00025_BGR'
        minimum_confidence_threshold: 0.7 #0.7
        generate_overlay: False
        overlay_dpi: 300 # int |FROM| 100 to 300
        overlay_background_color: 'black' # str |FROM| 'white' or 'black'

    # Configure Plant Component Detector
    armature_component_detector:
        # ./leafmachine2/component_detector/runs/train/detector_type/detector_version/detector_iteration/weights/detector_weights
        detector_type: 'Armature_Detector' 
        detector_version: 'ARM_A_1000'
        detector_iteration: 'ARM_A_1000'
        detector_weights: 'best.pt'
        minimum_confidence_threshold: 0.5 #0.2
        do_save_prediction_overlay_images: True
        ignore_objects_for_overlay: [] 

    landmark_detector_armature:
        # ./leafmachine2/component_detector/runs/train/detector_type/detector_version/detector_iteration/weights/detector_weights
        upscale_factor: 10
        
        detector_type: 'Landmark_Detector_YOLO' 
        detector_version: 'Landmarks_Arm_A_200'
        detector_iteration: 'Landmarks_Arm_A_200'
        detector_weights: 'last.pt'
        minimum_confidence_threshold: 0.06
        do_save_prediction_overlay_images: True ######################################################################################################
        ignore_objects_for_overlay: [] # list[str] # list of objects that can be excluded from the overlay # all = null
        use_existing_landmark_detections: null #'D:/Dropbox/LM2_Env/Image_Datasets/TEST_LM2/images_short_landmark/Plant_Components/Landmarks_Whole_Leaves_Overlay' # null for unprocessed images

        do_show_QC_images: True
        do_save_QC_images: True

        do_show_final_images: True
        do_save_final_images: True
    